language: c++
os:
  - osx
compiler:
  - clang
before_script:
  - cmake --version
  - clang --version
  - mkdir /Users/travis/build/fedorov/dcmqi-build
script:
  - cd /Users/travis/build/fedorov/dcmqi-build
  - cmake /Users/travis/build/fedorov/dcmqi
  - ls DCMQI-build
  - make
