language: c++
os:
- osx
env:
- CTEST_MODEL=Experimental
compiler:
- clang
before_script:
- cmake --version
- clang --version
- mkdir /Users/travis/build/QIICR/dcmqi-build
- cd /Users/travis/build/QIICR
- wget https://cmake.org/files/v3.4/cmake-3.4.3.tar.gz
- tar zxf cmake-3.4.3.tar.gz
- cd cmake-3.4.3
- ./configure && make
script:
- cd /Users/travis/build/QIICR/dcmqi-build
- /Users/travis/build/QIICR/cmake-3.4.3/bin/cmake /Users/travis/build/QIICR/dcmqi
- make
- cd /Users/travis/build/QIICR/dcmqi-build/dcmqi-build && /Users/travis/build/QIICR/cmake-3.4.3/bin/ctest -VV -DCTEST_MODEL=$CTEST_MODEL -DCTEST_EMPTY_BINARY_DIRECTORY=FALSE .
