language: c++
os:
- osx
env:
- CTEST_MODEL=Experimental
compiler:
- clang
before_script:
- clang --version
- npm install jsonlint -g
- npm install ajv-cli -g
- wget --no-check-certificate http://www.dclunie.com/dicom3tools/workinprogress/macexe/dicom3tools_macexe_1.00.snapshot.20160721064406.zip -O dicom3tools.zip
- tar zxf dicom3tools.zip
- mv dciodvfy /usr/local/bin/
- pwd && mkdir -p /Users/travis/build/QIICR/dcmqi-build
- cd /Users/travis/build/QIICR
- wget --no-check-certificate https://cmake.org/files/v3.5/cmake-3.5.2.tar.gz
- tar zxf cmake-3.5.2.tar.gz
- mv cmake-3.5.2 cmake-build
- cd cmake-build
- ./configure && make
script:
- cd /Users/travis/build/QIICR/dcmqi-build
- /Users/travis/build/QIICR/cmake-build/bin/cmake /Users/travis/build/QIICR/dcmqi
- make
- cd /Users/travis/build/QIICR/dcmqi-build/dcmqi-build && /Users/travis/build/QIICR/cmake-build/bin/ctest -VV -DCTEST_MODEL=$CTEST_MODEL -DCTEST_EMPTY_BINARY_DIRECTORY=FALSE .
