version: 1.0.{build}
os:
  - Visual Studio 2013
clone_depth: 1
clone_folder: c:\dcmqi
configuration:
  - Debug
platform:
  - x64
install:
  - cinst cmake
before_build:
  - cmd: cmake --version
  - cmd: mkdir c:\dcmqi-build
  - cmd: cd c:\dcmqi-build
  - cmd: cmake c:\dcmqi
  - cmd: dir
build_script:
  - cmd: msbuild DCMQI.sln
cache:
  - C:\ProgramData\chocolatey\bin
  - C:\ProgramData\chocolatey\lib
