version: 0.0.{build}
os:
  - Visual Studio 2013
clone_depth: 1
branches:
  only:
    - master
skip_tags: true
clone_folder: c:\dcmqi
install:
  - cinst cmake
configuration:
  - Release
platform:
  - x64
before_build:
  - cmd: cmake --version
  - cmd: mkdir c:\dcmqi-build
  - cmd: cd c:\dcmqi-build
  - cmd: cmake -G "Visual Studio 12 2013 Win64" -DCMAKE_BUILD_TYPE:STRING=Release c:\dcmqi
  - cmd: dir
after_build:
  - cmd: dir c:\dcmqi-build\ITK-build
  - cmd: dir c:\dcmqi-build\zlib-build
  - cmd: 7z a zlib-install.zip C:\dcmqi-build\zlib-install
  - cmd: appveyor PushArtifact zlib-build.zip
  - cmd: 7z a ITK-build.zip  C:\dcmqi-build\ITK-build\
  - cmd: appveyor PushArtifact ITK-build.zip
  - cmd: 7z a DCMTK-build.zip  C:\dcmqi-build\DCMTK-build\
  - cmd: appveyor PushArtifact DCMTK-build.zip
  - cmd: dir c:\
  - cmd: dir c:\dcmqi
build_script:
  - cmd: type DCMQI.sln
  - cmd: msbuild DCMQI.sln /m
cache:
  - C:\ProgramData\chocolatey\bin
  - C:\ProgramData\chocolatey\lib
