version: 1.0.{build}
os:
  - Visual Studio 2013
clone_depth: 1
clone_folder: c:\dcmqi
install:
  - cinst cmake
configuration:
  - Release
platform:
  - x64
before_build:
  - cmd: cmake --version
  - cmd: mkdir c:\dcmqi-build
  - cmd: cd c:\dcmqi-build
  - cmd: cmake -G "Visual Studio 12 2013 Win64" -DCMAKE_BUILD_TYPE:STRING=Release c:\dcmqi
  - cmd: dir
build_script:
  - cmd: type DCMQI.sln
  - cmd: msbuild DCMQI.sln /m
cache:
  - C:\ProgramData\chocolatey\bin
  - C:\ProgramData\chocolatey\lib
