version: 1.0.{build}
os:
  - Visual Studio 2013
clone_depth: 1
clone_folder: c:\dcmqi
install:
  - cinst cmake
configuration:
  - Release
platform:
  - x64
before_build:
  - cmd: cmake --version
  - cmd: mkdir c:\dcmqi-build
  - cmd: cd c:\dcmqi-build
  - cmd: cmake -G "Visual Studio 12 2013 Win64" -DCMAKE_BUILD_TYPE:STRING=Release c:\dcmqi
  - cmd: dir
build_script:
  - cmd: type DCMQI.sln
  - cmd: msbuild DCMQI.sln /m
cache:
  - C:\ProgramData\chocolatey\bin
  - C:\ProgramData\chocolatey\lib
artifacts:
  - path: dcmqi-build\ITK-build
    name: ITK-dcmqi-bin
    type: zip
  - path: dcmqi-build\DCMTK-build
    name: DCMTK-dcmqi-bin
    type: zip
deploy:
    provider: Github
    description: 'Test upload package of ITK-dcmqi-build zipped folder'
    artifact: ITK-dcmqi-bin
    auth_token:
      secure: ffHRHxe8buygkDl6kRw4vaNaH/ikYGoDn3TXfZ42cFXq7986houCT7/7qB8o5Vvf
